source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KDTree_Example' do
    platform :ios, '9.3'
    
    pod 'KDTree', :path => '../'
    pod 'SwiftyHYGDB', :path => '~/SwiftyHYGDB'
    pod 'SwiftyBeaver'
    
    target 'KDTree_Tests' do
        inherit! :search_paths
        
        pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'support-swift-4'
        pod 'Nimble', :git => 'https://github.com/Quick/Nimble', :branch => 'master'
    end
    
end


target 'KDTree_OSX_Example' do
    platform :osx, '10.10'

    pod 'KDTree', :path => '../'
    pod 'SwiftyBeaver'

    target 'KDTree_OSX_ExampleTests' do
        inherit! :search_paths
    end
end
