source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'KDTree_Example', :exclusive => true do
  pod 'KDTree', :path => '../'
  pod 'XCGLogger', '~> 3.3'
end

target 'KDTree_Tests', :exclusive => true do
  pod 'KDTree', :path => '../'

  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 4.0'
end
